const types = {

    //ui
    UI_OPEN_MODAL: 'UI_OPEN_MODAL',
    UI_CLOSE_MODAL: 'UI_CLOSE_MODAL',

    // eventos
    EVENT_SET_ACTIVE: 'EVENT_SET_ACTIVE',
    EVENT_UNSET_ACTIVE: 'EVENT_UNSET_ACTIVE',
    EVENT_ADD_NEW: 'EVENT_ADD_NEW',
    EVENT_UPDATED: 'EVENT_UPDATED',
    EVENT_DELETED: 'EVENT_DELETED',

    //autenticacion
    AUTH_CHECKING: 'AUTH_CHECKING',
    AUTH_CHECKIN_FINISH: 'AUTH_CHECKIN_FINISH',
    AUTH_START_LOGIN: 'AUTH_START_LOGIN',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_START_REGISTER: 'AUTH_START_REGISTER',
    AUTH_START_TOKEN_RENEW: 'AUTH_START_TOKEN_RENEW',
    AUTH_LOGOUT: 'AUTH_LOGOUT' 

}

export default types;