const types = {

    //ui
    UI_OPEN_MODAL: 'UI_OPEN_MODAL',
    UI_CLOSE_MODAL: 'UI_CLOSE_MODAL',

    // eventos
    EVENT_SET_ACTIVE: 'EVENT_SET_ACTIVE',
    EVENT_UNSET_ACTIVE: 'EVENT_UNSET_ACTIVE',
    EVENT_ADD_NEW: 'EVENT_ADD_NEW',
    EVENT_UPDATED: 'EVENT_UPDATED',
    EVENT_DELETED: 'EVENT_DELETED'

}

export default types;